### ISSUE TITLE
Enable multi status AppVeyor And Travis

### ISSUE THREAD

**Issue by alquerci** [nylen/cyg-apt#59]
Just follow http://github-multi-status.herokuapp.com/

@nylen I activate this on `alquerci/cyg-apt` send me a pull request to test.

**Comment by alquerci** [comment]
@nylen Since [GitHub has introduce multi-status][0] an utility for that is useless.

[0]: https://github.com/blog/1935-see-results-from-all-pull-request-status-checks

**Comment by nylen** [comment]
@alquerci if I understand correctly, I need to remove the `github-multi-status` web hook?  is there anything else I need to change?

**Comment by alquerci** [comment]
@nylen yes nothing else

**Comment by nylen** [comment]
Done.
